### ISSUE TITLE
Unable to run it on Openshift

### ISSUE THREAD

**Issue by talha0324** [openshift/verification-tests#2161]
Hey, I'm running openshift 4.7 on Openstack. Configured with SSO login via google.
I'm unable to run the tests.
These are the environment variables i've set.
```
BUSHSLICER_DEFAULT_ENVIRONMENT=ocp4
OPENSHIFT_ENV_OCP4_HOSTS=<MY_MASTER_NODE>:master
```
I run this command for the test `bundle exec cucumber features/logging/kibana.feature`.

I get the following error:
```
Host object was not created with :node specified. (RuntimeError)
      /mnt/d/otherRepos/verification-tests-master/lib/host.rb:932:in `node'
...
```

**Comment by pruan-rht** [comment]
@talha0324 the example in the README is outdated it should be api.<your_clusters_name> which can you get by
`oc get route -n openshift-console`

for example:
```
$ oc get route -n openshift-console
NAME        HOST/PORT                                                                    PATH   SERVICES    PORT    TERMINATION          WILDCARD
console     console-openshift-console.apps.kata-0712.qe.gcp.devcluster.openshift.com            console     https   reencrypt/Redirect   None
downloads   downloads-openshift-console.apps.kata-0712.qe.gcp.devcluster.openshift.com          downloads   http    edge/Redirect        None
```
so the resulting config should be 
`export OPENSHIFT_ENV_OCP4_HOSTS=api.kata-0712.qe.gcp.devcluster.openshift.com:lb`

**Comment by talha0324** [comment]
@pruan-rht what will be the host type for it?
I see a major missing part of a README. do you guys have some documentation somewhere?

**Comment by pruan-rht** [comment]
@talha0324 I'm not sure what you mean by `host type for it`... Using my example (sub out the url with your cluster), it should work for you.

**Comment by talha0324** [comment]
So there's a file in `config/config.yaml`
my config looks like this
```
environments:
  ocp4: &ocp4
    hosts: api.<my-cluster-address>.cloud:lb
    # hosts_type: OCDebugAccessibleHost
    # this is the user for remote access to the OpenShift nodes
    user: root
    type: StaticEnvironment
    user_manager: auto
    # set users in OPENSHIFT_ENV_OCP4_USER_MANAGER_USERS=user:password,...
    # user_manager_users: joe:redhat,alice:redhat
    #cli: MasterOsPerUserCliExecutor
    cli: SharedLocalCliExecutor
    admin_creds: AutoKubeconfigCredentials
    api_port: 6443
    #version: 4.1.0.0 # version not supported on cluster (yet)
```
But I still get an error:
```
no implicit conversion of nil into String (TypeError)
      /mnt/d/otherRepos/verification-tests-master/lib/environment.rb:591:in `const_get'
      /mnt/d/otherRepos/verification-tests-master/lib/environment.rb:591:in `parse_hosts_spec'
      /mnt/d/otherRepos/verification-tests-master/lib/environment.rb:527:in `hosts'
      /mnt/d/otherRepos/verification-tests-master/lib/environment.rb:81:in `block (2 levels) in <class:OpenShiftEnvironment>'
      /mnt/d/otherRepos/verification-tests-master/lib/admin_credentials.rb:39:in `master_host'
      /mnt/d/otherRepos/verification-tests-master/lib/admin_credentials.rb:45:in `get'
      /mnt/d/otherRepos/verification-tests-master/lib/admin_credentials.rb:97:in `get'
      /mnt/d/otherRepos/verification-tests-master/lib/environment.rb:113:in `admin'
      /mnt/d/otherRepos/verification-tests-master/lib/world.rb:124:in `admin'
      /mnt/d/otherRepos/verification-tests-master/features/step_definitions/user.rb:15:in `/^I switch to cluster admin pseudo user$/'
      /mnt/d/otherRepos/verification-tests-master/features/step_definitions/transform.rb:33:in `call'
      /mnt/d/otherRepos/verification-tests-master/features/step_definitions/transform.rb:33:in `block in singleton class'
      /mnt/d/otherRepos/verification-tests-master/features/step_definitions/logging.rb:33:in `/^logging operators are installed successfully$/'
      /mnt/d/otherRepos/verification-tests-master/features/step_definitions/transform.rb:33:in `call'
      /mnt/d/otherRepos/verification-tests-master/features/step_definitions/transform.rb:33:in `block in singleton class'
      /mnt/d/otherRepos/verification-tests-master/features/support/clusterlogging_env.rb:3:in `Before'
```
